apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: spanreplay
  annotations:
    eks.amazonaws.com/role-arn: configured-by-kustomize-replacement
automountServiceAccountToken: true
